# Generated by Django 3.1.2 on 2023-01-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_auto_20220716_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(default=None, max_length=255, verbose_name='slug'),
        ),
    ]
